name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install pip-tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Compile requirements
      shell: bash
      run: |
        if [ -f requirements.in ]; then
          pip-compile requirements.in --upgrade
        fi
        if [ -f requirements-dev.in ]; then
          pip-compile requirements-dev.in --upgrade
        fi
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: 'chore: Update Python Dependencies'
        body: |
          This PR updates Python dependencies to their latest versions.
          
          Please review the changes and ensure tests pass before merging.
        branch: automated/dependency-updates
        delete-branch: true
        labels: dependencies, automated
